### ISSUE TITLE
Is there a way to use fcitx5/ibus in gamescope?

### ISSUE THREAD

**Issue by l12436** [ValveSoftware/gamescope#1067]
when I open game or editor in gamescope, I can only type Englilsh
fcitx5/ibus did not working ?
Is there anything need to setup or it is not supported yet?
I can not even copy-paste word into it.

Test command

gamescope -- kwrite
gamescope -- wine notepad

**Comment by Joshua-Ashton** [comment]
Hello, I believe the Steam On-Screen Keyboard should work for typing CJK in Gamescope, but ibus etc in nested won't work right now I think.

It currently just uses SDL for keyboard when nested -- if you understand what would be needed to set stuff up such that IMEs work there, feel free to PR or give details.

**Comment by l12436** [comment]
I did not run gamescope with steam, so.... there maybe no onscreen keyboard could use.
So It is normal that current IME is not able to use under gamescope ?

**Comment by Joshua-Ashton** [comment]
Right now, that is likely expected.

**Comment by l12436** [comment]
OK thanks for the information

**Comment by yigekuyou** [comment]
qdbus6 org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.OpenX11Connection :0
or DISPLAY=:0 /usr/bin/fcitx5-remote --check -x

**Comment by l12436** [comment]
> qdbus6 org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.OpenX11Connection :0 or DISPLAY=:0 /usr/bin/fcitx5-remote --check -x

I have tried, Is this working under kde5 x11 ? or just kde6 wayland ?

**Comment by sg-qwt** [comment]
> > qdbus6 org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.OpenX11Connection :0 or DISPLAY=:0 /usr/bin/fcitx5-remote --check -x
> 
> I have tried, Is this working under kde5 x11 ? or just kde6 wayland ?

You need to check which DISPLAY your gamescope is using, in my case after I run `DISPLAY=:1 fcitx5-remote -x`, the input is half working again. I say half working because the candidate selection box is missing inside gamescope's steam in my case. Also, would you please reopen the issue, I don't see why this should be closed.

**Comment by northernorca** [comment]
Sorry for the necroposting, but I figured out kind of a hack that can work with steam+gamescope:
```
gamescope -W 2560 -H 1440 -w 2560 -h 1440 -f -- env LD_PRELOAD="$LD_PRELOAD" XMODIFIERS=@im=kime bash -c 'kime-xim & sleep 0.5; exec "$@"' -- %command%
```
Ignore the width/height/fullscreen options and `LD_PRELOAD` envs as they are irrelevant to this issue. The part after that is what matters.

This is done with a korean IME kime and tested only with DJMAX RESPECT V, but a similar workaround should also be possible with any IMEs compatible with XIM (i.e. changing `@im=kime` to `@im=fcitx` and executing `fcitx5` instead of `kime-xim`).

Probably `sleep 0.5` is not necessary.
