### ISSUE TITLE
Crashing upon force closing DOOM Eternal

### ISSUE THREAD

**Issue by Sterophonick** [ValveSoftware/gamescope#1087]
# System Information
Gamescope verson: `3.13.19-2`
SteamOS Version: `20240104.1000`
Hardware: Steam Deck OLED

# Description of Issue
I seem to be having an issue where the Gamescope session will crash upon force quitting DOOM Eternal in Steam. I do not have any background software injecting into Steam running.

Currently unsure if any other games are affected but DOOM Eternal was the one game I found to be 100% consistent.

# Correct Behavior
No crash.

# Log / Core Dump
[Coredump](https://github.com/ValveSoftware/gamescope/files/13838494/gamescope_13849.zip)
[`coredumpctl` log](https://github.com/ValveSoftware/gamescope/files/13838498/gamescope_13849_log.txt)
[`gdb` backtrace](https://github.com/ValveSoftware/gamescope/files/13838500/gamescope_13849_bt.txt)

**Comment by sharkautarch** [comment]
@Sterophonick hmmm looking at the gdb backtrace, it looks like gamescope’s crashing is triggered when calling `content_overrides.find(…)` in function `gamescope_xwayland_server_t::destroy_content_override( struct wlserver_x11_surface_info *x11_surface, struct wlr_surface *surf )` in wlserver.cpp

assuming that this likely isn’t due to a bug in the c++ standard library, the only reason I can think of for why this is crashing would be due to a race condition on the content_overrides variable…
@Joshua-Ashton what do you think of this?

**Comment by Sterophonick** [comment]
Did some more testing. It does not matter if HDR is enabled, and it also occurs when docked.

**Comment by Sterophonick** [comment]
Currently fixed, presumably by https://github.com/ValveSoftware/gamescope/commit/676a069d15e0caeb3937da9ceb814b5e24dd9844 and https://github.com/ValveSoftware/gamescope/commit/decc450d2a8a189ebd99db37233649990aa8085d
