### ISSUE TITLE
Holding down a key causes it to spam click instead of remaining held down

### ISSUE THREAD

**Issue by DoomSlinger** [ValveSoftware/gamescope#1183]
In most games I've tested, if you hold down a key, it spam clicks it (sometimes in random intervals) instead of just keeping the key held down.

OS: Arch Linux x86_64 
Kernel: 6.7.8-arch1-1 
Shell: bash 5.2.26 
DE: Plasma 6.0.1 
WM: kwin 
CPU: AMD Ryzen 7 5800X (16) @ 3.800GHz 
GPU: AMD ATI Radeon RX 7900 XT/7900 XTX/7900M 
Memory: 7361MiB / 32018MiB

I don't really know what else to add here, don't really know how to troubleshoot this issue either.

Edit: Noticed that the issue only occurs when installing via the arch repository. Building from here or downloading the git version from the AUR doesn't have this issue. Instead these 2 versions have an issue where if I alt-tab, then tab back in, I can no longer use the keyboard to interact with the ui in several games. (for example, can't open or type in the chatbox in warframe)

Edit: figured out the alt-tab issue is a problem with the alt key getting stuck when alt tabbing. Pressing alt again fixes it.

**Comment by zeparu** [comment]
can confirm same behaviour, noticed it on FFXIV, also installed the official arch package

**Comment by Joshua-Ashton** [comment]
Does it work in latest Gamescope master for you now?

**Comment by zeparu** [comment]
tried it just now on arch with the `gamescope-git` package, and holding down keys behaves normally again for me

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by awsms** [comment]
I'm still having this issue, in BF4 for example if I do `Shift+W` it spams W instead of just keeping it held.
Sometimes it even *stops* recognizing W after a few secs. Dunno if that's relevant to this specific issue but it sounds very similar.
edit: holding the tab key spams it instead of holding it as well, no need for a modifier. 😆
for the reference I'm on Hyprland, gamescope ran with `gamescope -w 3840 -h 2160 --backend sdl  -- %command%`, and using latest gamescope-git (currently 3.16.19.r5.g1164ac17-1)

re: made a [tiny gui](https://github.com/awsms/keywatch) program that tells when a key was press/held/released. when running it in a gamescope session with SDL backend, it considers the key is released then retyped every time. i can reproduce every single time when ran in gamescope (`gamescope --backend sdl -- ./keywatch`)

re: can't reproduce it on i3, just on Hyprland
