### ISSUE TITLE
Mouse Input Issue version gamescope-3.14.2-1

### ISSUE THREAD

**Issue by odakaui** [ValveSoftware/gamescope#1184]
Hello,

I am having an issue with mouse input using gamescope version `3.14.2-1`.
My issue goes away when I downgrade to `3.14.0-1`.
I run all my games using steam.

I tested gamescope using two different games.
The issue is different depending on the game.

## Helldivers 2

I am unable to turn my camera more than 90 degrees.
My camera is locked to a specific range and will stop moving at the ends of the range even if I continue to move my mouse.

## Darktide 40k

My camera is stuck looking at the floor, and it spins around with any movement, even with my in game sensitivity at its lowest setting.

## Note 

Both games work fine when run without gamescope. 
Both games work fine when run under `gamescope-3.14.0-1`.

Distro: 6.7.8-arch1-1
Window Manager: Sway
CPU: 5900x
GPU: 6700xt

If you need more information, I'll be happy to add it.

Thank you for your time!

**Comment by notpeelz** [comment]
Duplicate of #1141

**Comment by sharkautarch** [comment]
> Hello,
> 
> I am having an issue with mouse input using gamescope version `3.14.2-1`. My issue goes away when I downgrade to `3.14.0-1`. I run all my games using steam.
> 
> I tested gamescope using two different games. The issue is different depending on the game.
> ## Helldivers 2
> 
> I am unable to turn my camera more than 90 degrees. My camera is locked to a specific range and will stop moving at the ends of the range even if I continue to move my mouse.
> ## Darktide 40k
> 
> My camera is stuck looking at the floor, and it spins around with any movement, even with my in game sensitivity at its lowest setting.
> ## Note
> 
> Both games work fine when run without gamescope. Both games work fine when run under `gamescope-3.14.0-1`.
> 
> Distro: 6.7.8-arch1-1 Window Manager: Sway CPU: 5900x GPU: 6700xt
> 
> If you need more information, I'll be happy to add it.
> 
> Thank you for your time!


to add to what notpeelz said, for now, you can just install the [`gamescope-git`](https://aur.archlinux.org/packages/gamescope-git) package from the AUR to get a newer version that has the fix to this issue

I would say that this issue should be closed, since it is already fixed in upstream,
**except** that [the latest release version](https://github.com/ValveSoftware/gamescope/releases/tag/3.14.2) doesn't have the fix yet 
@Joshua-Ashton could you please create a new release version targeting https://github.com/ValveSoftware/gamescope/commit/14a1db3a57612e5cfbba6d4c19688eafdc6c4043 and/or just the latest commit (idk how stable the new wayland backend is atm)
thanks

**Comment by odakaui** [comment]
Awesome! Thank you so much! Should I close this or leave it open?

**Comment by sharkautarch** [comment]
> Awesome! Thank you so much! Should I close this or leave it open?

Hmmm probably close it and I’ll just make a new issue asking Joshua Ashton to make a new release if he doesn’t see my comment

**Comment by odakaui** [comment]
Ok. Will do!
