### ISSUE TITLE
[3.14.2] GTA V camera panning broken

### ISSUE THREAD

**Issue by SysError99** [ValveSoftware/gamescope#1198]
On latest `3.14.2` release, Gamescope breaks camera panning in Grand Theft Auto V.

https://github.com/ValveSoftware/gamescope/assets/17522480/213c0c91-4829-4832-9740-6bf09e61c2f0

**Comment by Eckoa** [comment]
This has been fixed in master already, 

might be this commit https://github.com/ValveSoftware/gamescope/commit/a5d853accd176d8ff8bb4c5d54b4b4cd8053b4d7

but i know for certain it has  been as of https://github.com/ValveSoftware/gamescope/commit/14a1db3a57612e5cfbba6d4c19688eafdc6c4043 which is what my build is using. You can build it yourself or wait till your distro updates it.

**Comment by SysError99** [comment]
Confirmed fixed in `3.14.16`, and could be earlier than this version.
