### ISSUE TITLE
[3.14.16] FSR doesn't work with KDE Wayland

### ISSUE THREAD

**Issue by SysError99** [ValveSoftware/gamescope#1360]
Hardware: AMD Ryzen 5 2500U with AMD Radeon Vega 8 Graphics (VivoBook_ASUS Laptop X505ZA_X505ZA)
Software: 6.1.92-1-MANJARO with KDE Plasma 6.0.5 Wayland
Gamescope version: 3.14.16

Running Gamescope with FSR enabled caused the screen to flicker in full screen and be broken in windowed mode. Running it in X11 seems to work fine.

Might be related to #1356

**Comment by SysError99** [comment]
This is still replicable up to the master.

**Comment by L1Q** [comment]
The workaround for now seems to be using the SDL backend through ``--backend=sdl`` argument

**Comment by QuinsZouls** [comment]
Same issue here using Wayland and nvidia 555. 
I can't use workaround because it's broken on nvidia.

**Comment by thegreatzach** [comment]
I am also having an issue with FSR. I'm running on both desktop (AMD 6800 GPU) Bluefin and steam deck(LCD) Bazzite. Both are using GNOME 46 with Wayland. When using FSR gamescope will launch but the image becomes a white blown out image that does not play properly at all.

Desktop is being ran inside of an Arch distrobox reporting `console: gamescope version 3.14.22` . Bazzite is reporting reporting `console: gamescope version 3.14.24+`. The workaround of `--backend=sdl` has worked for me as well. 

Steam deck works perfectly in gamemode, but looking at other `--backend` options that would more so be `drm` or `headless`. This issue seems to only exist when in desktop/nested mode. Does not matter if fullscreen, boarderless, or windowed. Using other scaling options also fixes the described issue. Both `nis` and `pixel` work without issue. 

Command:
`gamescope --backend wayland -w 1920 -h 1080 -W 2560 -H 1440 -F fsr -f -r 144 -- vkcube`

**Comment by nozwock** [comment]
I was wondering why the `--backend sdl` workaround was not working for me. Turns out that the `=` is very important here, `--backend=sdl` works just fine. Weird.

**Comment by murkl** [comment]
On Arch + GNOME with `--backend=sdl` works also fine. If Game does not open in fullscreen i have to add `SDL_VIDEODRIVER=x11`
