### ISSUE TITLE
Game Mode: Lower contrast when pointer is visible at 4K resolution

### ISSUE THREAD

**Issue by AkazaRenn** [ValveSoftware/gamescope#1485]
### Describe the bug

In Game Mode, when the pointer (cursor) is visible, the screen seems to have lower contrast. Seems only happening in 4K resolution. If I start the game in 1440P it works normally.
Here's the recording I made with a capture card (please ignore the audio):
https://github.com/user-attachments/assets/faa679e4-d9c4-4034-8af8-245e64944e93

### What did you expect to happen?

The image should keep consistent whether the pointer is visible or not. According to my experience, when the pointer disappears the image seems to be the correct one.

### Hardware
Steam Deck OLED 512 GB

### Software
Steam OS 3.6.9 build 20240814.100
Steam version 1723685248

### Extra information or context

1. It seems only happen in Game Mode, starting the same game in desktop mode doesn't have that issue, even if I've enabled "hiding cursor when inactive" in the settings
2. The games I tested were: _The Legend of Zelda: Tears of the Kingdom_ (Ryujinx), _Final Fantasy XIV Online_ (XIVLauncher), _Overwatch 2_ (Steam), they cover both Steam and non-Steam games and all have this issue, even including the Steam BPM itself
3. I've tested turning on/off the following and none had fixed the issue: HDR, VRR, performance overlay, game recording, scaling, half rate shading, 120Hz<->60Hz

**Comment by matte-schwartz** [comment]
Is this happening on multiple AMD GPUs? The clip looks like it's from a 6950XT. I think 6xxx series amdgpus should use direct scan-out even with HDR, except for when you invoke a cursor, similar to vangogh.

I suspect you're maybe running into the results of this workaround  https://github.com/ValveSoftware/gamescope/blob/f554d886093ad3fdc361b4642fe6cca4cdaa99b1/src/Backends/DRMBackend.cpp#L73-L81 which changes how shaders and LUTs get used between scan-out and compositing (like when you invoke the cursor). Although it's a bit odd since I'm not able to see the same issue yet on my own OLED Deck when docked to my 4K TV @ 60hz... I'll try checking in some games later.

If you enable developer settings from within Game Mode, can you enable `Composite Debug`? This will show QR code looking squares in the top of the screen whenever gamescope starts compositing. If they don't appear, then gamescope is using direct-scan out. If using scan-out, then can you see if either `Force Composite` or `Disable Color Management` have any effect on this issue? I suspect it may start to happen globally in Game Mode if you `Force Composite`

**Comment by AkazaRenn** [comment]
@matte-schwartz 
Thank you for the detailed explanation!

First to explain my situation, originally this glitch was observed on my desktop running Bazzite OS, that's where the recording comes from. After verifying with my Deck, I confirmed that this is a Gamescope issue so posted it here.

However, by testing again today with my Deck, I can no longer see the issue...

As for `Force Composite`, it works! The behavior differs from your description for some reason, when I turn on `Composite Debug`, the squares appears together with my pointer, I assume that means Gamescope switches to direct scan when my pointer is hidden?

Anyway, after turning on `Force Composite`, the image quality is consistent now, however, on the worse side. Per my comparison, the image quality from direct scan is higher, at least on FFXIV. Is there possibly a way to fix it without sacrificing the image quality?
