### ISSUE TITLE
Mouse stuck in a square at the center of the screen

### ISSUE THREAD

**Issue by dougg0k** [ValveSoftware/gamescope#1540]
Hi,

I was trying out the tool, most things seem to work, even though mangoapp only initialized later on. 

Main problem is mouse stuck on the center of the screen in a square manner. 

```
gamescope --version
[gamescope] [Info]  console: gamescope version 3.15.5
```

```
gamescope -w 2560 -h 1440 --fullscreen --mangoapp --sdr-gamut-wideness --hdr-enabled --hdr-sdr-content-nits 1000 --adaptive-sync --nested-refresh 360 --immediate-flips --expose-wayland
```

I tried out `--force-grab-cursor`, it does make the cursor not be stuck, but it is too inaccurate, I thought to use `--mouse-sensitivity` with a value lower than 1, as it was very loose and fast, the result was the same at a lower sensitivity, which didnt really help.

Good tool, except for this.

**Comment by hfc2x** [comment]
What game are you running? Because the `-w` and `-h` parameters are for forcing in-game resolution. If your monitor's resolution is 1440p, then you have to use `-W` and `-H`, otherwise you'll experience weird glitches (or even crashes) if the game doesn't have a way of changing its own resolution without fan-made hacks or patches.

For example, I play Diablo II (the original version, not Resurrected) with Gamescope, and I use `-W 1920 -H 1080` to force the game to stretch to my monitor's resolution while keeping its original resolution, but because it's inherently an 800x600 game, it cannot really be forced to run at a higher resolution. Diablo II is also one of those games that cause the mouse to misbehave, so it requires `--force-grab-cursor` to work properly.

Once you set that, you need to set `--mouse-sensitivity` properly. In my case, I use `--mouse-sensitivity 0.55`, because 600/1080 (original game's vertical resolution divided by monitor's vertical resolution) is 0.555555555. Setting it like this makes the mouse feel very natural, and it moves at the same speed as it does in my desktop.

For a game that runs at 800x600, in your 1440p monitor, you need to set this parameter to 0.42 for the speed to be right. You just need to know the resolution the game is internally running at.

**Comment by dougg0k** [comment]
RDR2 running at 2560x1440, but has DLSS ON, if that matters.

**Comment by hfc2x** [comment]
I have no idea if Gamescope works with DLSS. Try running with `-W 2560 -H 1440 -w 2560 -h 1440 -f` and without `--mouse-sensitivity` to see if it makes any difference. Forcing Gamescope to run at native monitor resolution has often solved most issues for me.

**Comment by dougg0k** [comment]
Tried with just `-H and -W` and it was worse, went like a smaller center square. And tried with both, same issue.

**Comment by dougg0k** [comment]
Tried `--mouse-sensitivity` with `--force-grab-cursor` again and it's plain bad implemented, it's like there is negative acceleration making it even worse.
