### ISSUE TITLE
F key toggles fullscreen mode

### ISSUE THREAD

**Issue by OlegAckbar** [ValveSoftware/gamescope#1637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using any gamescope patches or a forked version of gamescope?

- [X] The issue occurs on upstream gamescope without any modifications

### Current Behavior

When I press F games in with "exclusive fullscreen" mode gamescope toggles its fullscreen mode. Just F without any modifiers.

### Steps To Reproduce

1. Launch any games that use exclusive fullscreen
2. Press F
3. Gamescope will turn to window mode instead of being fullscreen. No modifiers are used.

### Hardware information

```markdown
Operating System: Arch Linux 
KDE Plasma Version: 6.2.3
KDE Frameworks Version: 6.8.0
Qt Version: 6.8.0
Kernel Version: 6.12.1-2-cachyos (64-bit)
Graphics Platform: Wayland
Processors: 8 × Intel® Core™ i7-7700K CPU @ 4.20GHz
Memory: 15.6 ГиБ of RAM
Graphics Processor: AMD Radeon RX 6700 XT
```

### Software information

```markdown
- Gamescope version: 3.15.9.r22.g37a348be-1
- Gamescope launch command(s): `gamescope --mangoapp --hdr-enabled -w 2560 -h 1440 -W 2560 -H 1440 -f --force-grab-cursor --`
```

### Which gamescope backends have the issue you are reporting?

- [X] Wayland (default for nested gamescope)
- [ ] DRM (default for embedded gamescope, i.e. gamescope-session)
- [ ] SDL
- [ ] OpenVR

**Comment by matte-schwartz** [comment]
Someone reported this for Stalker 2 but it worked on my machine when I tried to get it to happen. does it happen in any other particular games?

**Comment by OlegAckbar** [comment]
I also had this problem in Stalker 2, but now I can't reproduce it. This also was happening in Deus Ex: Revision. I guess it only happens under some condition which is yet to be found.

**Comment by OlegAckbar** [comment]
Someone encountered same problem on reddit: https://www.reddit.com/r/linux_gaming/comments/1gxn5fr/wine_wayland_woes/

**Comment by NoXPhasma** [comment]
This seems to be related to the numpad. When I turn off the numpad, the F key won't toggle fullscreen anymore.

**Comment by byndthgrve** [comment]
Turning off num-lock also solved the issue for me as well. While running gamescope and num-lock enabled, the "F" key would toggle fullscreen. I also had other keys that would be unusable such as "S" and "O". If not using gamescope and num-lock was enabled. All keys worked normally.

**Comment by matte-schwartz** [comment]
Is everyone experiencing this using Plasma, or has it happened to anyone on other DEs as well?

**Comment by byndthgrve** [comment]
I'm on Plasma 6.2.3.

**Comment by matte-schwartz** [comment]
I'm on Plasma 6.2.3 on Arch and have run into the issue as well. 

Initially I was trying to look for some trigger for it happening, like launching gamescope from the Steam launch options or some other program interfering, but I had it happen immediately after a reboot without Steam autostarting, simply with `gamescope -f -- vkcube`. I rebooted again to see if I could still reproduce the issue afterwards, but on that boot cycle the hotkeys were working perfectly again under identical circumstances.

Unless I hear otherwise, it makes me wonder if we're hitting a bug somewhere else in Plasma that's being expressed by gamescope's hotkey usage tbh. Probably won't have time to look into it myself for a few days but I do think getting some input logs out of KDE would be good to see if they line up with what I see in Gamescope when I add logging for when various "Meta + [x]" functions get called within gamescope.

**Comment by jbellionjourdan** [comment]
Same issue here in several games.

This seems to be indeed a gamescope bug; it appears in several games i have tested and immediately vanishes when launching the same games without gamescope.

Disabling numpad works too for me as a temporary workaround but this is not convenient, hope this gets a fix.

Let me know if i can help providing logs or testing stuff.

**Comment by matte-schwartz** [comment]
@jbellionjourdan which desktop environment/session type?

```
~
❯ echo $XDG_CURRENT_DESKTOP 
KDE

~
❯ echo $XDG_SESSION_TYPE
wayland

```

**Comment by jbellionjourdan** [comment]
Wayland, KDE Plasma 6.

On Garuda linux (arch).

**Comment by matte-schwartz** [comment]
I spent around 20 minutes trying to reproduce the issue on Gnome (Wayland) but I was unable to, so I'm leaning towards this being some bug between KDE and gamescope. I will look for any related reports about hotkey issues on KDE's bug tracker and file a new issue if I don't find any.

**Comment by jbellionjourdan** [comment]
Yeah might be.

On my side it's pretty straightforward to reproduce, if numlock is on then gamescope shortcuts behave as if meta was always pressed.
If i turn off numlock then everything acts as normal (except the numpad, obviously).

Don't need to restart the game either, just pressing the numlock key instantly toggles the issue on and off.

**Comment by matte-schwartz** [comment]
I see the issue with `gamescope -- vkcube` on KDE without issue, just trying to narrow down sources.

**Comment by matte-schwartz** [comment]
For now I've reported the issue here: https://bugs.kde.org/show_bug.cgi?id=497050

I want to keep testing Gnome for a bit just to double-check that the issue really never happens there.

**Comment by naxil** [comment]
yes KDE here same problem.. shorcuts not work on latest gamescope

**Comment by jarrard** [comment]
Seems disable numpad works for me also.  
I can't reproduce the bug in basic vkcube setup however.  Might be a fullscreen app issue.

**Comment by Dinjoralo** [comment]
I'm using a version of Gamescope that should have commit [85937ea](https://github.com/adamdmoss/gamescope-ubuntu24/commit/85937ea468cdce83a8373e7eb795154ff930cad8), and I still have this issue. Every hotkey fires off regardless of if I'm holding the Super key. I'm on CachyOS using KDE plasma.

Seeing the comments here, when I'm at my PC I will check if this is related to NumLock being enabled per the KDE bug report.

**Comment by matte-schwartz** [comment]
Hmm, that is very odd since I wrote and tested the fix from CachyOS... are you sure you compiled a version of Gamescope that has it? It's not in a release version yet.

**Comment by Dinjoralo** [comment]
I believe so? CachyOS has the package being gotten from the [cachyos-v3-extra repo](https://mirror.cachyos.org/repo/x86_64_v3/cachyos-extra-v3/), which says it's on version "3.16.1-1.1", which isn't an actual release, and was built on Jan 2nd, the day when the last commits to master were made. I think the repo is compiling what's in Master when there are commits regardless of if there's been a release.

It's totally possible that I'm an idiot and assuming wrong, I'll see if I can compile Gamescope myself to see if the behavior persists. 

Oh, and the behavior is fixed by having NumLock off, so it is related to the bug that might be in the Wayland stack that's mentioned in the KDE bug report.
