### ISSUE TITLE
Possible to copy paste into gamescope windows?

### ISSUE THREAD

**Issue by hschen2** [ValveSoftware/gamescope#303]
It seems that gamescope windows have isolated copy and paste, i was wondering if theres any way i can copy from outside gamescope into it?, right now i cant copy my password for example into the gamescope window. Ty for your help. Im running on Sway if it matters

**Comment by emersion** [comment]
Yeah, I think clipboard sync is something we'll want to have at some point.

**Comment by d10sfan** [comment]
This would be beneficial on the steam deck as well

**Comment by aksdb** [comment]
While only a workaround, I wrote [a tool](https://github.com/aksdb/gamescopetool) that will run gamescope for you, launching a process outside of gamescope and within gamescope that use a unix socket to transmit clipboard changes. Therefore you effectively have a working clipboard in gamescope.

**Comment by pierregil33** [comment]
I'm using flatpak steam with com.valvesoftware.Steam.Utility.gamescope
is there a way to get working clipboard in game ?
Don't see how I can use your script to make this

**Comment by pierregil33** [comment]
> While only a workaround, I wrote [a tool](https://github.com/aksdb/gamescopetool) that will run gamescope for you, launching a process outside of gamescope and within gamescope that use a unix socket to transmit clipboard changes. Therefore you effectively have a working clipboard in gamescope.

I don't sucess to use this (arch linux, with steam and gamescope 3.11.30-1 from AUR).
may I copy the gamescopetool file somewhere ?

Also, I prefere to use flatpak steam with com.valvesoftware.Steam.Utility.gamescope
Is there a way to get it working for flatpak ?

**Comment by aksdb** [comment]
> > While only a workaround, I wrote [a tool](https://github.com/aksdb/gamescopetool) that will run gamescope for you, launching a process outside of gamescope and within gamescope that use a unix socket to transmit clipboard changes. Therefore you effectively have a working clipboard in gamescope.
> 
> I don't sucess to use this (arch linux, with steam and gamescope 3.11.30-1 from AUR). may I copy the gamescopetool file somewhere ?
> 
> Also, I prefere to use flatpak steam with com.valvesoftware.Steam.Utility.gamescope Is there a way to get it working for flatpak ?

You can copy it whereever you want. It should be fine.
I am not using flatpak, so I have no way to verify the workings, but from what I know, as long as you have access to the executable of `gamescopetool` from within the flatpak sandbox and if `gamescope` is in the `$PATH` within that sandbox, it should work just the same.

`gamescopetool` is currently relatively dumb. It will just launch `gamescope` (that's why gamescope has to be in the `$PATH`) and pass the path to itself as the first argument to launch (that's why it doesn't matter where `gamescopetool` is located).

Settings for a game I launch in steam are for example: `/home/myuser/bin/gamescopetool -w 1920 -h 1090 -f -- %command%`. If your homedirectory is available from within flatpak, the same thing should work for you.

**Comment by pierregil33** [comment]
> 

I paste gamescopetool side to gamescope in `/usr/bin` and chown it to my user, now it works.
trying to do same for flatpak under : `/var/lib/flatpak/runtime/com.valvesoftware.Steam.Utility.gamescope/x86_64/stable/active/files/bin`, this don't work.
I don't know why but at least 1 solution works.
thank you

**Comment by xrishox** [comment]
would love to see this implemented
