### ISSUE TITLE
Default screenshot hotkey registers keydown in game but not key up leading to temporarily stuck key in game.

### ISSUE THREAD

**Issue by NolanSyKinsley** [ValveSoftware/gamescope#577]
Super+S sends the S key press down event to the game but not key press up, or or rather doesn't suppress the down event. This leads to in some games the character running down, the screen moving, or whatever is bound to the S key in the game activating until the S key pressed a second time after the screenshot is taken.

**Comment by CartoonFan** [comment]
I think I've experienced this as well. Wasn't aware that the hotkey was used for screenshots, though (I use it for OBS).

**Comment by bwyan86** [comment]
I have also experienced this. Using swaywm, this specific hotkey also conflicts with my desktop config. It would be great if these hotkeys could be either configurable or disabled entirely.

**Comment by Arian04** [comment]
just wanted to let anyone that comes across this know that my PR (#923) got merged to fix this. So if it's still affecting you once a release comes out with that commit included, make sure you're updated. And if it's affecting you right now you might wanna build from source. It would also be cool if the person who made this issue could close it since it's resolved, thanks!

**Comment by kisak-valve** [comment]
Closing per the last comment.
