### ISSUE TITLE
Random crashes in Cyberpunk 2077

### ISSUE THREAD

**Issue by kostadinsh** [ValveSoftware/gamescope#696]
After some random time of playing Cyberpunk 2077, it could be minutes or a few seconds, the game just crashes after a certain input(it's always random).

OS: Gentoo
Kernel version: 6.1-rc7-tkg-cfs
GPU and Mesa version: RX 6800, mesa-git(55ffbf86)
Proton version: Proton Experimental
Gamescope version: 3.11.49

```
[xcb] Unknown sequence number while processing queue
[xcb] You called XInitThreads, this is not your fault
[xcb] Aborting, sorry about that.
gamescope: /var/tmp/portage/x11-libs/libX11-1.8.2-r1/work/libX11-1.8.2/src/xcb_io.c:278: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
(EE) failed to read Wayland events: Connection reset by peer

```
```
gamescope: /var/tmp/portage/x11-libs/libxcb-1.15-r1/work/libxcb-1.15/src/xcb_conn.c:223: write_vec: Assertion `!c->out.queue_len' failed.
```

The first log is from steam, ran from the terminal and the second one is the log from Proton

[steam.log](https://github.com/Plagman/gamescope/files/10148487/steam.log)
[steam-1091500.log](https://github.com/Plagman/gamescope/files/10148488/steam-1091500.log)

**Comment by kostadin04** [comment]
https://gitlab.freedesktop.org/xorg/lib/libx11/-/issues/170

I think this could be related?

**Comment by akien-mga** [comment]
> [gitlab.freedesktop.org/xorg/lib/libx11/-/issues/170](https://gitlab.freedesktop.org/xorg/lib/libx11/-/issues/170)
> 
> I think this could be related?

Yes, this is likely. See also https://github.com/ValveSoftware/steam-for-linux/issues/8977 which is probably the same issue.

@Plagman Basically libX11 1.8.3 (and previously libX11 1.8.2 + some upstream patches backported) seems to break gamescope (and also happens to break all Godot games, which is why I'm looking into it).
1.8.3 was released yesterday and pushed to Arch Linux - something to keep in mind when upgrading SteamOS (so far distros like OpenSUSE opted for sticking to libX11 1.8.1: https://bugzilla.opensuse.org/show_bug.cgi?id=1205818#c33 ).
