### ISSUE TITLE
[Feature Request] Sharp Bilinear upscaling option for pixel-art games.

### ISSUE THREAD

**Issue by Siam-Lights** [ValveSoftware/gamescope#712]
Would it be possible to implement an option to use the [Sharp-Bilinear-Simple GLSL shader](https://github.com/rsn8887/Sharp-Bilinear-Shaders/blob/master/Copy_To_RetroPie/shaders/sharp-bilinear-simple.glsl) on gamescope for better upscaling of pixel-art games?
The point of this shader is to remove pixel shimmering caused by uneven pixels when games are upscaled to non-integer resolutions. [Magpie](https://github.com/Blinue/Magpie) has already implemented this, but that's a Windows-only application at the moment.
![Sharp bilinear example](https://user-images.githubusercontent.com/97821031/207461117-9a181a43-71cf-43ee-b893-da999eb6bf6a.jpg)

**Comment by sonic2kk** [comment]
Just curious: Is this different from Integer scaling / Nearest Neighbor scaling? I haven't done any sort of extensive testing but `-n` improves the look of pixel art games to my eyes (e.g. Mega Man Legacy Collection) -- But I also haven't looked to deeply into it so it's possible there are various differences here.

**Comment by ticky** [comment]
> Is this different from Integer scaling / Nearest Neighbor scaling?

Yes, this permits games taller than 400 pixels to have a clean looking upscale. For example, many RPG Maker VX Ace games are 416 pixels tall, so they cannot be integer scaled up to the Steam Deck's 800 pixels, for example. With nearest neighbour scaling, these generally have a less than pleasing appearance, with jagged looking uneven pixels as they swap between one and two pixels wide and tall, depending on the row or column.

Would absolutely love to see this option!

**Comment by Siam-Lights** [comment]
As ticky said, nearest will cause a nasty pixel shimmering which is ugly by itself in still images but can be quite jarring in motion once you notice it/if you're sensitive to it. This is because nearest neighbor only cares about filling the screen with no filtering, so it'll stretch pixels in order to get the image to fit. Simple-Bilinear uses a mix of nearest + bilinear. One pass upscales to integer with nearest neighbor, and the second pass upscales the rest with bilinear (from what I understand).
![stretched vs nonstretched](https://user-images.githubusercontent.com/97821031/207997117-ac69c753-7752-4f42-bb53-68f2b8728d17.png)

**Comment by Siam-Lights** [comment]
Oops, slip of the finger.
As ticky said, nearest neighbor by itself can cause an ugly pixel shimmering on non-integer resolutions. It's ugly by itself and can look even more jarring in motion. Sharp-Bilinear upscales the image in two passes from what I understand. One is a nearest neighbor upscale to an integer scale, and the second upscales the rest with bilinear.
![stretched vs nonstretched](https://user-images.githubusercontent.com/97821031/207997766-28fb460b-2620-4bff-b9d4-b31e06ed2a29.png)

**Comment by sonic2kk** [comment]
> For example, many RPG Maker VX Ace games are 416 pixels tall, so they cannot be integer scaled up to the Steam Deck's 800 pixels, for example.

Ahh, I didn't consider Steam Deck and this limitation.

<hr>

Thanks for the image in the reply too.

What about GameScope's Integer scaling option though, with `-i`? If this is the same as Integer Scaling, does GameScope's integer scaling need improved (perhaps to use the mentioned shader in the OP)?

**Comment by ticky** [comment]
Here's a visual example I have prepared. Due to the Steam Deck not taking PNG screenshots I have prepared these examples in an image editor, but they use the same scaling algorithms we are discussing.

**Please note** that these images are _likely_ downscaled in your browser within this GitHub comment (unless you click on them), and will not be accurate if you are viewing these images on a _high density_ display (i.e. Retina display, Windows scaled to something other than 100%, etc.), or if they're displayed at a different scale in GitHub comments. On such devices, please consider opening these images in an image editor to view them at 1:1 scale.

---

Consider for example this screenshot of [an RPG Maker VX Ace game](https://ponett.itch.io/slarpgdemo). It is exactly 640 by 418 pixels high:

![Q3AoP3@1x](https://user-images.githubusercontent.com/282113/208209620-a31ea12e-eb36-4ec5-9da5-d263176156b1.png)

On Steam Deck, this currently looks like this by default (scaled to 800 pixels high, black borders on left and right omitted):

![Q3AoP3@1x@800h-bilinear](https://user-images.githubusercontent.com/282113/208209908-0bc13175-568f-4ead-a514-b2cf6270a2f4.png)

Take particular note of the blurry looking character outlines and the extra fuzzed out text.

Scaling to 800 pixels high with Nearest Neighbour would result in this:

![Q3AoP3@800h-nearest](https://user-images.githubusercontent.com/282113/208210533-3f99aa5d-1078-45ad-ac8b-f3186c70ed90.png)

Note the unevenly shaped and sized pixels, most obvious on diagonal or curved lines like the edges of the fountain.

Here is the same screenshot, but first nearest-neighbour scaled to 816 pixels high, and then secondly bilinear scaled down to 800, equivalent to the Sharp Bilinear algorithm described in OP's shader (and available in emulators such as RetroArch for other games):

![Q3AoP3@800h-sharp-bilinear](https://user-images.githubusercontent.com/282113/208210061-54d1484e-05ea-418f-bfef-510569148474.png)

This image has perceptually better-preserved detail, and the sharpness of the pixel artwork is preserved. It's also beneficial versus nearest neighbour in motion, as it is not subject to a visual shimmering effect as details pass over the unevenly sized pixels.

Scaling graphics is obviously subjective, dependent on the game, and this one is _my own_ preference, but I _very_ much prefer the "sharp bilinear" look to the others in this situation.

**Comment by sonic2kk** [comment]
Thanks for the visual examples, I'm still not sure how this Sharp Bilinear filter is different from the `-i` flag you can pass to GameScope (which I think would be equivalent to Steam Deck's `Integer` option).

I agree that scaling is subjective and here I have no real preference between the last two screenshots, I'm moreso interested in how it differs from regular integer scaling. Particularly I'm interested because, is this filter something that should be changed with the integer scaling option already available in GameScope?

**Comment by ticky** [comment]
The Integer option on Steam Deck/Gamescope would display this at the original scale of 640 by 418, with black bars and unused space on all sides, because there is no integer multiple of 418 which fits within 800.

**Comment by ticky** [comment]
>This doesn't actually need a two-pass solution

I hope I didn't give the impression that was _required_ on the implementation end, I was just noting my methodology for simulating the appearance.

**Comment by Joshua-Ashton** [comment]
I added `--filter pixel` which uses this method https://themaister.net/blog/2018/08/25/pseudo-bandlimited-pixel-art-filtering-in-3d-a-mathematical-derivation/ but simplified for 2D.

It also limits the extent to 0.25 atm, but I would like to make that configurable at some point.

**Comment by ticky** [comment]
I notice as of the SteamOS 3.5.5 release (congrats to the team by the way!) that the build of `gamescope` includes this filter (maybe I missed it in an earlier stable release, not sure, only thought to check now), but it's not exposed in the Steam Deck UI, is there a way to enable it at run time or will it require invoking `gamescope` explicitly per game to adjust?

**Comment by DPS2004** [comment]
I was wondering now that the Steam Deck UI has replaced the nearest neighbor filter with the pixel filter described in this issue, is there any way to access the nearest neighbor filter instead? As said earlier, what scaling method looks "best" is very subjective, and I prefer the nearest neighbor scaling for the vast majority of usecases. 

If possible, I think a good solution would be to have them both be selectable in the UI, but a command line option to use nearest neighbor instead would also be appreciated greatly.

**Comment by layercak3** [comment]
>command line option to use nearest neighbor

`-S nearest`
