### ISSUE TITLE
Gamescope crashes when using pipewiresrc 

### ISSUE THREAD

**Issue by safijari** [ValveSoftware/gamescope#845]
Reporting https://github.com/ValveSoftware/SteamOS/issues/1000 here as well as it seems to be the more relevant place. This breaks the `decky-recorder` plugin as well as possibly other usecases on the Deck.

**Comment by kisak-valve** [comment]
Hello @safijari, there's no value in fragmenting the discussion of SteamOS#1000 across multiple issue reports. If it makes more sense to discuss that issue report on this issue tracker, then explain that on SteamOS#1000 and give me a ping requesting the issue report be transferred to this issue tracker.

From looking around a bit, it sounds like this issue is also being tracked at #775 and is a regression in pipewire which needs to be evaluated and resolved upstream.

Closing as a duplicate.
