### ISSUE TITLE
Moving camera with cursor in FFXIV with XIVLauncher is really bad

### ISSUE THREAD

**Issue by yaomtc** [ValveSoftware/gamescope#919]
This issue cropped up after the 3.12 update on Arch Linux. Was working fine before.

https://youtu.be/ysYQtXqAlIM

**Comment by WardenPotato** [comment]
Yeah im experiencing the same issue on garrysmod now, it seems to be related to the fact that setting a cursor position through a game is no longer accepted (as it normally would under wayland) which causes issues

**Comment by yaomtc** [comment]
That did it, thanks!

Also noticed on 3.12, the icon for FFXIV shows up on the task bar, while on previous versions it's the X11 icon (assuming because gamescope doesn't have an icon itself)

**Comment by yaomtc** [comment]
Turns out I have this issue with XIVLauncher (uses custom Wine builds such as GE-Proton) not with the vanilla FFXIV launcher via regular Proton

**Comment by fuyuki94370** [comment]
Want to add some personal information:

Regardless of gamescope is being used or not, this bug is only observed when FFXIV is run using GE Proton 8-25 on KDE Wayland (and Wayland in general looking at reports); it happens with vanilla FFXIV or XIVLauncher from AUR / Flatpak, and it doesn't happen with the custom wine that comes with XIVLauncher, nor does it happen with Proton 8.0-4 from Valve.

My vague memory says it used to happen with the custom wine (back when the latest Valve Proton is 8.0-2 or so), but I tested today and it's gone now, making GE Proton the only one that still has this bug.

So, this is probably not an bug from gamescope. 
I recall that gamescope doesn't manage its mouse pointer anymore and in a sense uses the HW cursor from the OS after certain timepoint (see #196 ); that's probably why the camera bug "appears" in the first place.

**Comment by yaomtc** [comment]
I should have specified back when I posted this that I was using Gamescope to get around an issue with Plasma (Wayland), and after that particular update Gamescope was no longer a valid workaround.


It happens to me with the Wine version set to "Managed by XIVLauncher" but only when I'm clicking on the window after it's unfocused, and not every time (at least half, I'd guess). 

They suggest it should go away with the Wayland driver in Wine 9. I will test this.

**Comment by yaomtc** [comment]
Yes, Wine 9 Wayland fixes the issue I was using Gamescope to work around.

Also, Wine 9 Wayland works with Gamescope, though I personally no longer have a reason to nest a Wayland compositor within a Wayland compositor.
