### ISSUE TITLE
[Feature Request] Expose zoomScaleRatio as a command-line option

### ISSUE THREAD

**Issue by mmatis** [ValveSoftware/gamescope#929]
On steam deck, the Magnifier feature scales the screen about +50%. I *think* this is controlled by the [zoomScaleRatio float in steamcompmgr.cpp](https://github.com/ValveSoftware/gamescope/blob/4c788db880784ad300e90d585b26aca2a7b1af57/src/steamcompmgr.cpp#L698), though I'm not sure where that default of +50% magnification comes from. There are many cases where this level of magnification is not enough for people with visual impairments. It's probably too much to ask for this to get added as an option in the Steam Client, but it would be an excellent start if gamescope made the default magnifier zoom scale configurable via a command-line option. Even better would be zoom in/out hotkeys so it can be changed on-the-fly mid-game.

**Comment by Lvsoar** [comment]
I had a glance through the code and found this:

`if ( zoomScaleRatio != 1.0 )
	{
		scaledX += ((sourceWidth / 2) - winX) * currentScaleRatio_x;
		scaledY += ((sourceHeight / 2) - winY) * currentScaleRatio_y;
	} `

If I’m not mistaken, this is dividing the source window in half and adding that to the current window scale. There are other references to how it handles the overscan, cursor and so on. But if you could build a plugin to change this math to add more than just 50% (Removing the /2?) would give you a 200% zoom.

it seems like zoomScaleRatio might be an obfuscated book value rather than a true integer.

the code also references something to do with atoms.screenZoomAtom and SCREEN_MAGNIFICATION_PROP but I have no idea what they are referencing.

NB. I only have a rudimentary understanding of code but I’m tired of this being ignored, and the number of games with unnecessarily small text is slowly edging people like me with vision impairments out of gaming entirely.

**Comment by arkareth** [comment]
Well, I've had enough of this as well and thrown together a workaround that lets zooming in as much as one needs in Gaming mode: https://github.com/arkareth/steam-deck-improved-magnification

Readme is a bit messy, but you should be able to figure it out.

I hope this helps until Valve (hopefully) comes up with a proper solution, folks. Any questions or help needed - just let me know.

**Comment by lostgoat** [comment]
Thanks for the suggestion.

The steam client now exposes a configurable zoom ratio under settings-> display.

**Comment by mmatis** [comment]
> Well, I've had enough of this as well and thrown together a workaround that lets zooming in as much as one needs in Gaming mode: https://github.com/arkareth/steam-deck-improved-magnification
> 
> Readme is a bit messy, but you should be able to figure it out.
> 
> I hope this helps until Valve (hopefully) comes up with a proper solution, folks. Any questions or help needed - just let me know.

Absolute HERO!!! (and thanks for the shout-out!)
