### ISSUE TITLE
meson is a mess

### ISSUE THREAD

**Issue by clemens98** [ValveSoftware/gamescope#943]
Run-time dependency libpipewire-0.3 found: NO (tried pkgconfig and cmake)
Library rt found: YES
Run-time dependency hwdata found: YES 0.366
Run-time dependency x11 found: YES 1.7.5
Run-time dependency vulkan found: YES 1.3.204
Run-time dependency openvr found: NO (tried pkgconfig and cmake)

meson.build:51:4: ERROR: Subproject exists but has no CMakeLists.txt file

meson refuses to make a build directory 
it dosent find libpipewire despite it being installed

**Comment by clemens98** [comment]
linux mint  21.1    libwire 0.3.48

**Comment by simifor** [comment]
do you have the "-dev" version of libpipewire installed?

**Comment by sonic2kk** [comment]
Just built gamescope a few minutes ago (cf19852ce333fb2a23cc18077b63ed55578d9839) and had no issues on Arch Linux. I have pipewire 0.3.79 though.

The build files seem to [only specify requiring pipewire 0.3](https://github.com/ValveSoftware/gamescope/blob/master/meson.build#L37-L38). Maybe this is a different issue than simply the pipewire version, unless it's common for applications not to find Pipewire with older releases?

**Comment by clemens98** [comment]
Should I have the dev Version?

**Comment by simifor** [comment]
dev is short for development, you need it to compile stuff with it

**Comment by clemens98** [comment]
Run-time dependency openvr found: NO (tried pkgconfig and cmake)

meson.build:51:4: ERROR: Subproject exists but has no CMakeLists.txt file

good that was it   but now i am still left with these 2

**Comment by simifor** [comment]
Maybe there's a problem with your local files? you can see here https://github.com/ValveSoftware/gamescope/tree/master/layer that there's a meson.build file in the layer folder, your error suggests that in _your_ folder there isn't one. How did you download the project? And what steps are you following to compile it?

**Comment by clemens98** [comment]
git submodule update --init
meson build/

just code    download zip

**Comment by simifor** [comment]
you mean this? 
![Screenshot 2023-09-12 at 17-00-59 ValveSoftware_gamescope SteamOS session compositing window manager](https://github.com/ValveSoftware/gamescope/assets/70454800/5d49e5e4-da73-430b-b0c8-c918cc7e2e20)
Aren't you getting an error when running `git submodule update --init` ? I don't think the "Download ZIP" will give you something that counts as a valid git tree, so I'd expect the first build command to fail.

**Comment by clemens98** [comment]
fatal: not a git repository (or any parent up to mount point /mnt)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by simifor** [comment]
yeah, you need to use git clone to get the source code
`git clone https://github.com/ValveSoftware/gamescope/`
this will create a gamescope folder in your terminal's current directory (your home folder if you didn't change it), you cd into that folder and then follow the build instructions.

**Comment by clemens98** [comment]
Run-time dependency xres found: NO (tried pkgconfig and cmake)

src/meson.build:8:0: ERROR: Dependency "xres" not found, tried pkgconfig and cmake

**Comment by sonic2kk** [comment]
Seems you need a newer Wayland Server package version. You have 1.20.0, Gamescope seems to require 1.21.0 (and the latest available version, as far as I can see, is 1.22.0).

I'm not sure how to update this on Linux Mint, or what provides it on your system (I don't think Mint uses Wayland by default? Maybe only for its greeter if I read that correctly a while back).

If something core to Mint has a hard dependency on Wayland 1.20 you may not be able to build Gamescope from source on Linux Mint.

<hr>

On the other hand, is no one providing a prebuilt Gamescope package on Linux Mint?

**Comment by clemens98** [comment]
nope and the version i am using no longer works

**Comment by sonic2kk** [comment]
Your best bet then is to try to update the `wayland` package (which should provide wayland-server). You should check where it comes from and what depends on it, and if it is safe to update. If there is no pinned version that a package depends on, it may be that the newer package is not available on your distribution yet.

Looking at the [Wayland website's Releases section](https://wayland.freedesktop.org/releases.html), it seems 1.20.0 was released on December 9th, 2021. This lines up with when Arch Linux started packaging this newer release, [which was a few days later](https://gitlab.archlinux.org/archlinux/packaging/packages/wayland/-/commit/3750222a7803a2997b6a433cff5c10e07c56405b) (I mention Arch because it generally updates packages very quickly).

It would be interesting to know what is providing you with such an outdated version of the `wayland` package (or whatever it is named on Mint). I can't find much information about Mint and Wayland packaging, though I know by default Linux Mint does not use Wayland.

In short, the version of Wayland in use here is out-of-date, and will need to be updated before you can build Gamescope. I would also check to ensure you have the relevant dependencies outlined in Gamescope's [`meson.build`](https://github.com/ValveSoftware/gamescope/blob/cf19852ce333fb2a23cc18077b63ed55578d9839/src/meson.build) file. The main ones i can see at a glance are listed below. Keep in mind that package names may differ, so look around for the correct one on your distribution.
- `libdrm` - 2.4.113 or above
- `wayland-server` - 1.21 or above
- `wayland-protocols` - 1.17.0 or above (may need to be installed separately to the Wayland package itself)
- `wlroots` - `>= 0.16.0` and `<= 0.17.0` (in other words, between these two version ranges inclusive, so 0.16.0 and 0.17.0 are both fine, as are any versions in-between, but anything higher or lower than these bounds will not work)
- `libdisplay-info` - `>= 0.0.0` and `< 0.2.0` (unlike the above, this is exclusive, meaning 0.2.0 will not work, it has to be a version *below* 0.2.0)
- `libliftoff` - `>= 0.4.0` and `< 0.5.0` (in this case, anything 0.4.0 will work, but 0.5.0 will not, so anything between 0.4.0 and 0.5.0 *including* 0.4.0 but *not* including 0.5.0)

In case I missed any, please review the [`meson.build`](https://github.com/ValveSoftware/gamescope/blob/cf19852ce333fb2a23cc18077b63ed55578d9839/src/meson.build) file yourself. Worst case scenario you can keep attempting to build and checking/updating dependencies as needed.

**Comment by simifor** [comment]
The most current linux mint release seems to based on ubuntu 22.04 which has wayland-server 1.20, wayland-server 1.21 was added on 22.10. Looking at mint's release schedule, it'll take around a year until the next version comes out.

So you'll have to find a way to compile the dependencies, switch distros, or wait until the next linux mint version comes out.

**Comment by sonic2kk** [comment]
Less than ideally it may also be possible to attempt to build an older version of gamescope that is compatible with wayland-server 1.20. You could look at the file history of the meson dependencies to try and figure out the latest commit you can build from, then copy the hash and run `git checkout` and paste the hash in. I assume it built successfully before if you were using Gamescope already and if there is no way to use Gamescope on Linux Mint without compiling from source.

This approach may come with its own set of challenges, for example you may have dependencies which are *too new* for an older release. Be sure to check the packages you have installed and their versions, and compare this with what an older build of Gamescope needs. If your packages do end up being too new, I would **not** recommend trying to downgrade them, as this will likely break things.

If you have to stick with Mint and you have to use Gamescope, you might be better off asking on the Linux Mint forums about this, in case there's a way to use a prebuild `gamescope-bin` type package.

**Comment by clemens98** [comment]
Well older versions of GameScope isn't an Option becouse no one is providing those
The Release thing on GitHub is empty
Looks like I also need to Update meson before updating Wayland

Will probably do that tomorrow evenings or the evening after that have lots of work Right now in rl

**Comment by sonic2kk** [comment]
> Well older versions of GameScope isn't an Option becouse no one is providing those

What do you mean? Unless I'm missing something, this is more than possible. Just because there are no releases, that doesn't mean something isn't being provided, the commits have not gone anywhere. All you have to do is find a commit with an older Wayland dependency as mentioned, and perhaps Meson dependency now too (Gamescope currently requires [Meson 0.58.0 or above](https://github.com/ValveSoftware/gamescope/blob/cf19852ce333fb2a23cc18077b63ed55578d9839/meson.build#L5)). Check the file history for the `meson.build` file to find the latest version with the older Wayland dependency.

I just did this quickly, and it seems the minimum Meson version was bumped to `0.58.0` in c11051534554cb5310bfdb7ba3e8dfe5d9cf0f76. The `meson.build` file in this commit [does not specify a Wayland version](https://github.com/ValveSoftware/gamescope/blob/c11051534554cb5310bfdb7ba3e8dfe5d9cf0f76/meson.build#L39). It does, however, specify `wayland-protocols >= 1.17`, so make sure this is met. We're onto Wayland Protocols 1.32 now, so I suspect even Mint with these very old packages will meet this dependency. The Wayland version was not bumped until 343e286308b01a6945b1913e854c5a628de47bfd, from September 10th 2022. Again, this is over a year old.

This means:
- If you can't satisfy `meson 0.58.0` or above, build from the latest version with the older Meson version dependency AND no Wayland version dependency: 429107e193ee8e21517028b8627afd75de78dcd3
- If you have Meson 0.58.0 or above, though, you can use the latest version without any Wayland version dependency, c40c8aa48263a69597d7f0250623bc10d77e9d47

If you have never done this before:
```sh
git clone https://github.com/ValveSoftware/gamescope
cd gamescope
git checkout <commit_hash>  # replace <commit_hash> with the relevant commit from above
git submodule update --init
meson build/
ninja -C build/
meson install -C build/ --skip-subprojects
```

Gamescope doesn't have any packaged releases at all, distributions which do package them generally do so [based on the tags](https://github.com/ValveSoftware/gamescope/tags), or offer a git package which is generally up-to-date. Some distributions provide builds of Gamescope with additional patches, too.

Building from source for most projects shouldn't really be the go-to solution for many reasons; you need to manage all the dependencies yourself, as well as making sure they're all up-to-date, and this is difficult to do on a point-release distribution like Linux Mint. A package manager is ideal here, which should provide a prebuilt binary. I would strongly suggest asking around the Linux Mint community to see how they're doing this, as I don't think you're the only person wanting to use Gamescope on Linux Mint, and I'm sure this problem has been resolved somehow already :-)

**Comment by simifor** [comment]
https://github.com/akdor1154/gamescope-pkg/releases @clemens98 this has packages aimed at ubuntu (mint is based on ubuntu, so I'd expect it to work if you're on mint 21), as always exercise caution when downloading from the internet, and you might want to try and use the build scripts instead, but it's up to you in the end.

**Comment by clemens98** [comment]
> https://github.com/akdor1154/gamescope-pkg/releases @clemens98 this has packages aimed at ubuntu (mint is based on ubuntu, so I'd expect it to work if you're on mint 21), as always exercise caution when downloading from the internet, and you might want to try and use the build scripts instead, but it's up to you in the end.

thank you very much exactly what i was looking for
